ENTITY_GROUP_PLAYER: str = 'player'
ENTITY_GROUP_ENEMY: str = 'enemy'
ENTITY_GROUP_BULLET: str = 'bullet'
ENTITY_GROUP_OBSTACLE: str = 'obstacle'
ENTITY_GROUP_ITEM: str = 'item'

ALL_ENEMY_GROUPS: list[str] = [ENTITY_GROUP_PLAYER, ENTITY_GROUP_ENEMY, ENTITY_GROUP_BULLET, ENTITY_GROUP_OBSTACLE, ENTITY_GROUP_ITEM]

STATUS_EFFECT_POISON: str = 'poison'
STATUS_EFFECT_BURNED: str = 'burned'
STATUS_EFFECT_REGENERATION: str = 'regeneration'
STATUS_EFFECT_SLOWNESS: str = 'slowness'
STATUS_EFFECT_PARALYZED: str = 'paralyzed'
STATUS_EFFECT_FROZEN: str = 'frozen'
STATUS_EFFECT_PETRIFIED: str = 'petrified'
STATUS_EFFECT_SPEED: str = 'speed'
STATUS_EFFECT_DAZED: str = 'dazed'
STATUS_EFFECT_STUNNED: str = 'stunned'
STATUS_EFFECT_BERSERK: str = 'berserk'
STATUS_EFFECT_SICKENED: str = 'sickened'
STATUS_EFFECT_INVINCIBLE: str = 'invincible'
STATUS_EFFECT_ARMOR_BROKEN: str = 'armor_broken'
STATUS_EFFECT_ARMORED: str = 'armored'
STATUS_EFFECT_VIVACIOUS: str = 'vivacious'
STATUS_EFFECT_HEALTH_BOOST: str = 'health_boost'
STATUS_EFFECT_CURSED: str = 'cursed'
STATUS_EFFECT_ENLARGED: str = 'enlarged'
STATUS_EFFECT_MINIFIED: str = 'minified'

ALL_STATUS_EFFECTS: list[str] = [STATUS_EFFECT_POISON, STATUS_EFFECT_BURNED, STATUS_EFFECT_REGENERATION, STATUS_EFFECT_SLOWNESS, STATUS_EFFECT_PARALYZED,
                                 STATUS_EFFECT_FROZEN, STATUS_EFFECT_PETRIFIED, STATUS_EFFECT_SPEED, STATUS_EFFECT_DAZED, STATUS_EFFECT_STUNNED, STATUS_EFFECT_BERSERK,
                                 STATUS_EFFECT_SICKENED, STATUS_EFFECT_INVINCIBLE, STATUS_EFFECT_ARMOR_BROKEN, STATUS_EFFECT_ARMORED, STATUS_EFFECT_VIVACIOUS,
                                 STATUS_EFFECT_HEALTH_BOOST, STATUS_EFFECT_CURSED, STATUS_EFFECT_ENLARGED, STATUS_EFFECT_MINIFIED]
